#!/bin/bash
#
# 個人理財助理 — Claude Code Plugin Installer
#
# Usage: ./install.sh [--output-dir <path>]
#
# This script installs the stock analysis plugin so it can be used
# from ANY directory in Claude Code. Just type "分析台積電" anywhere.
#

set -e

SKILLS_DIR="$HOME/.claude/skills"
OUTPUT_DIR="$HOME/fubon-stock-reports"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$HOME/.claude/stock-analysis.conf"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --help|-h)
      echo "Usage: ./install.sh [--output-dir <path>]"
      echo ""
      echo "Options:"
      echo "  --output-dir  Custom output directory for reports (default: ~/fubon-stock-reports)"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Resolve to absolute path
OUTPUT_DIR="$(cd "$(dirname "$OUTPUT_DIR")" 2>/dev/null && pwd)/$(basename "$OUTPUT_DIR")" 2>/dev/null || OUTPUT_DIR="$HOME/fubon-stock-reports"

SKILLS=(
  "stock-orchestrator"
  "stock-data-fetcher"
  "stock-data-validator"
  "stock-financial-analyst"
  "stock-technical-analyst"
  "stock-quant-analyst"
  "stock-industry-macro"
  "stock-news-sentiment"
  "stock-institutional-flow"
  "stock-integrator"
  "stock-dashboard"
)

echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║    個人理財助理 — Claude Code Plugin      ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""
echo "  Skills directory : $SKILLS_DIR"
echo "  Output directory : $OUTPUT_DIR"
echo ""

# Step 1: Create directories
mkdir -p "$SKILLS_DIR"
mkdir -p "$OUTPUT_DIR"

# Step 2: Install Python dependencies
echo "📦 Installing Python dependencies..."
python3 -m pip install -r "$SCRIPT_DIR/requirements.txt" --quiet 2>/dev/null || \
  pip install -r "$SCRIPT_DIR/requirements.txt" --quiet
echo "   ✓ Python dependencies installed"
echo ""

# Step 3: Copy skill directories & replace path placeholders
echo "🔧 Installing skills..."
for skill in "${SKILLS[@]}"; do
  if [ -d "$SCRIPT_DIR/$skill" ]; then
    # Clean previous install
    rm -rf "$SKILLS_DIR/$skill"
    # Copy fresh from source
    cp -r "$SCRIPT_DIR/$skill" "$SKILLS_DIR/$skill"
    # Replace placeholders in SKILL.md with absolute paths
    if [ -f "$SKILLS_DIR/$skill/SKILL.md" ]; then
      sed "s|{{SKILLS_DIR}}|$SKILLS_DIR|g; s|{{OUTPUT_DIR}}|$OUTPUT_DIR|g" \
        "$SKILLS_DIR/$skill/SKILL.md" > "$SKILLS_DIR/$skill/SKILL.md.tmp" && \
        mv "$SKILLS_DIR/$skill/SKILL.md.tmp" "$SKILLS_DIR/$skill/SKILL.md"
    fi
    echo "   ✓ $skill"
  else
    echo "   ✗ $skill (not found, skipping)"
  fi
done

# Step 4: Write config file
cat > "$CONFIG_FILE" << EOF
# 個人理財助理 — Configuration
# Generated by install.sh on $(date)
#
# To change output directory, re-run:
#   ./install.sh --output-dir /your/custom/path

STOCK_ANALYSIS_SKILLS_DIR=$SKILLS_DIR
STOCK_ANALYSIS_OUTPUT_DIR=$OUTPUT_DIR
INSTALLED_FROM=$SCRIPT_DIR
EOF
echo ""
echo "   ✓ Config saved to $CONFIG_FILE"

# Step 5: Done
echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "  ✅ Installation complete!"
echo ""
echo "  Open Claude Code in ANY directory and try:"
echo "    分析台積電"
echo "    analyze AAPL"
echo "    幫我看看鴻海"
echo ""
echo "  Reports will be saved to:"
echo "    $OUTPUT_DIR/{stock_name}/"
echo ""
echo "  To uninstall:"
echo "    ./uninstall.sh"
echo ""
echo "═══════════════════════════════════════════════"
